#!/usr/bin/env bash
# Pfun V2 Completion Specification -- S0 task 1.
#
# Records the identity of the tree and the machine that produced a baseline.
# Kept separate from scripts/baseline-inventory.mjs because these values
# legitimately differ between machines, and mixing them into the inventory
# would destroy its byte-comparability.
#
# Usage:
#   bash scripts/baseline-environment.sh            # write baseline/environment.md
#   bash scripts/baseline-environment.sh --stdout   # print instead of writing

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

sha256() {
	if command -v sha256sum >/dev/null 2>&1; then
		sha256sum "$1" | cut -d' ' -f1
	else
		shasum -a 256 "$1" | cut -d' ' -f1
	fi
}

DIRTY=""
if ! git diff --quiet HEAD 2>/dev/null; then
	DIRTY=" (working tree has uncommitted changes)"
fi

render() {
	cat <<EOF
# Pfun V2 baseline environment

Generated by \`bash scripts/baseline-environment.sh\` (Completion Specification
S0 task 1). Unlike \`baseline/inventory.md\`, these values vary by machine and
are not expected to be byte-identical across hosts.

## Source identity

| Field | Value |
|---|---|
| Commit | \`$(git rev-parse HEAD)\`$DIRTY |
| Commit subject | $(git log -1 --pretty=%s) |
| Tree hash | \`$(git rev-parse HEAD^{tree})\` |
| Tracked \`.pf\` files | $(git ls-files '*.pf' | wc -l | tr -d ' ') |
| Tracked \`.pf\` lines | $(git ls-files '*.pf' | xargs wc -l | tail -1 | awk '{print $1}') |

## Seed compiler

| Field | Value |
|---|---|
| Path | \`boot/pfc.js\` |
| SHA-256 | \`$(sha256 boot/pfc.js)\` |
| Bytes | $(wc -c < boot/pfc.js | tr -d ' ') |

## Host

| Field | Value |
|---|---|
| Node | $(node --version) |
| npm | $(npm --version 2>/dev/null || echo "n/a") |
| Platform | $(uname -s) $(uname -r) |
| Architecture | $(uname -m) |
EOF
}

if [[ "${1:-}" == "--stdout" ]]; then
	render
else
	mkdir -p baseline
	render > baseline/environment.md
	echo "wrote baseline/environment.md"
fi
