#!/usr/bin/env bash
# GENERATED by gen-test-harness.js — do not edit by hand.
# mode=compile files=20 generated=2026-07-11T05:11:12.279Z
set -u

output_mode=normal
case "${1:-}" in
  --verbose) output_mode=verbose; shift ;;
  --summary) output_mode=summary; shift ;;
  "") ;;
  *) echo "Usage: $0 [--verbose|--summary]" >&2; exit 2 ;;
esac
if [ "$#" -ne 0 ]; then
  echo "Usage: $0 [--verbose|--summary]" >&2
  exit 2
fi

if [ "$output_mode" = "verbose" ]; then
  export PFUN_TEST_VERBOSE=1
else
  export PFUN_TEST_VERBOSE=0
fi

# Color only on an interactive terminal unless explicitly forced.
# FORCE_COLOR overrides NO_COLOR. TERM=dumb disables automatic color.
color_enabled=0
if [ -n "${FORCE_COLOR:-}" ] && [ "${FORCE_COLOR:-0}" != "0" ]; then
  color_enabled=1
elif [ -t 1 ] && [ -z "${NO_COLOR+x}" ] && [ "${TERM:-}" != "dumb" ]; then
  color_enabled=1
fi

if [ "$color_enabled" -eq 1 ]; then
  RED=$'\033[31m'
  GREEN=$'\033[32m'
  YELLOW=$'\033[33m'
  CYAN=$'\033[36m'
  BOLD_RED=$'\033[1;31m'
  BOLD_GREEN=$'\033[1;32m'
  RESET=$'\033[0m'
else
  RED=''
  GREEN=''
  YELLOW=''
  CYAN=''
  BOLD_RED=''
  BOLD_GREEN=''
  RESET=''
fi
export PFUN_TEST_COLOR="$color_enabled"
cd "$(dirname "${BASH_SOURCE[0]}")/../.." || exit 2
PROJECT_ROOT="$(pwd)"
export PFUN_HOME="${PFUN_HOME:-$PROJECT_ROOT}"
export PFUN_RUNTIME="$PROJECT_ROOT/src/runtime/pfun-runtime.js"
export PFUN_IO="$PROJECT_ROOT/src/runtime/pfun-io.js"

pass=0
fail=0
failed_files=()

show_full_output() {
  local f="$1"
  local log="$2"
  local status="$3"
  echo
  if [ "$status" = "pass" ]; then
    printf "%s=== %s ===%s\n" "$CYAN" "$f" "$RESET"
  else
    printf "%s=== %s ===%s\n" "$BOLD_RED" "$f" "$RESET"
  fi
  cat "$log"
}

show_pass_summary() {
  local f="$1"
  local log="$2"
  local suites_line
  suites_line="$(grep "^Suites:" "$log" | tail -n 1)"
  if [ -n "$suites_line" ]; then
    printf "%s -- %s%s%s\n" "$suites_line" "$CYAN" "$f" "$RESET"
  else
    printf "%sPASS%s -- %s%s%s\n" "$GREEN" "$RESET" "$CYAN" "$f" "$RESET"
  fi
}

run_one() {
  local f="$1"
  local log
  log="$(mktemp)"
  local rc=0
  local failure_kind=""
  local base
  base="$(basename "$f" .pf)"
  local outdir
  outdir="$(mktemp -d)"
  node dist/main.js -c "$f" -o "$outdir" >"$log" 2>&1
  local compile_rc=$?
  if [ "$compile_rc" -ne 0 ]; then
    rc="$compile_rc"
    failure_kind="compile"
    printf "%sCOMPILE FAILED:%s %s\n" "$BOLD_RED" "$RESET" "$f" >>"$log"
  else
    local js
    js="$(find "$outdir" -name "${base}.js" ! -path "*/lib/*" | head -1)"
    if [ -z "$js" ]; then
      rc=1
      failure_kind="no js"
      printf "%sNO OUTPUT JS:%s %s\n" "$BOLD_RED" "$RESET" "$f" >>"$log"
    else
      local jsdir
      jsdir="$(dirname "$js")"
      if [ -n "$PFUN_RUNTIME" ]; then
        mkdir -p "$jsdir/lib" "$outdir/lib"
        cp "$PFUN_RUNTIME" "$jsdir/lib/pfun-runtime.js" 2>/dev/null || true
        cp "$PFUN_RUNTIME" "$outdir/lib/pfun-runtime.js" 2>/dev/null || true
        [ -n "$PFUN_IO" ] && {
          cp "$PFUN_IO" "$jsdir/lib/pfun-io.js" 2>/dev/null || true
          cp "$PFUN_IO" "$outdir/lib/pfun-io.js" 2>/dev/null || true
        }
      fi
      timeout 90 node "$js" >>"$log" 2>&1
      rc=$?
    fi
  fi
  rm -rf "$outdir"

  if [ "$rc" -eq 0 ]; then
    pass=$((pass+1))
    if [ "$output_mode" = "summary" ]; then
      show_pass_summary "$f" "$log"
    else
      show_full_output "$f" "$log" pass
    fi
  else
    fail=$((fail+1))
    if [ -n "$failure_kind" ]; then
      failed_files+=("$f ($failure_kind)")
    else
      failed_files+=("$f (exit $rc)")
    fi
    show_full_output "$f" "$log" fail
  fi

  rm -f "$log"
}

run_one 'bootstrap/test/assertions_test_gen.pf'
run_one 'bootstrap/test/check_test_gen.pf'
run_one 'bootstrap/test/compat_test_gen.pf'
run_one 'bootstrap/test/diag_test_gen.pf'
run_one 'bootstrap/test/exhaust_test_gen.pf'
run_one 'bootstrap/test/iface_test_gen.pf'
run_one 'bootstrap/test/imapi_test_gen.pf'
run_one 'bootstrap/test/imaps_test_gen.pf'
run_one 'bootstrap/test/iofloor_test_gen.pf'
run_one 'bootstrap/test/lexer_test_gen.pf'
run_one 'bootstrap/test/listx_test_gen.pf'
run_one 'bootstrap/test/modgraph_test_gen.pf'
run_one 'bootstrap/test/optionx_test_gen.pf'
run_one 'bootstrap/test/parser_test_gen.pf'
run_one 'bootstrap/test/purity_test_gen.pf'
run_one 'bootstrap/test/resultx_test_gen.pf'
run_one 'bootstrap/test/runner_test_gen.pf'
run_one 'bootstrap/test/spec_test_gen.pf'
run_one 'bootstrap/test/strx_test_gen.pf'
run_one 'bootstrap/test/types_test_gen.pf'

echo
echo "========================================"
printf "Test files: %s%s passed%s, " "$GREEN" "$pass" "$RESET"
if [ "$fail" -eq 0 ]; then
  printf "%s0 failed%s\n" "$GREEN" "$RESET"
else
  printf "%s%s failed%s\n" "$RED" "$fail" "$RESET"
fi
if [ "$fail" -ne 0 ]; then
  echo
  printf "%sFailed:%s\n" "$BOLD_RED" "$RESET"
  for ff in "${failed_files[@]}"; do
    printf "  %s-%s %s\n" "$RED" "$RESET" "$ff"
  done
  exit 1
fi
printf "%sALL TEST FILES PASSED%s\n" "$BOLD_GREEN" "$RESET"
exit 0
