#!/usr/bin/env bash
# GENERATED by gen-test-harness.js — do not edit by hand.
# mode=compile  files=8  generated=2026-07-11T03:08:03.973Z
set -u
cd "$(dirname "${BASH_SOURCE[0]}")/../.." || exit 2
PROJECT_ROOT="$(pwd)"
export PFUN_HOME="${PFUN_HOME:-$PROJECT_ROOT}"
export PFUN_RUNTIME="$PROJECT_ROOT/src/runtime/pfun-runtime.js"
export PFUN_IO="$PROJECT_ROOT/src/runtime/pfun-io.js"

pass=0
fail=0
failed_files=()

run_one() {
  local f="$1"
  echo
  echo "=== $f ==="
  local base; base="$(basename "$f" .pf)"
  local outdir; outdir="$(mktemp -d)"
  node dist/main.js -c "$f" -o "$outdir" || { echo "COMPILE FAILED: $f"; fail=$((fail+1)); failed_files+=("$f (compile)"); return; }
  local js; js="$(find "$outdir" -name "${base}.js" ! -path "*/lib/*" | head -1)"
  if [ -z "$js" ]; then echo "NO OUTPUT JS: $f"; fail=$((fail+1)); failed_files+=("$f (no js)"); return; fi
  local jsdir; jsdir="$(dirname "$js")"
  if [ -n "$PFUN_RUNTIME" ]; then
    mkdir -p "$jsdir/lib" "$outdir/lib"
    cp "$PFUN_RUNTIME" "$jsdir/lib/pfun-runtime.js" 2>/dev/null || true
    cp "$PFUN_RUNTIME" "$outdir/lib/pfun-runtime.js" 2>/dev/null || true
    [ -n "$PFUN_IO" ] && { cp "$PFUN_IO" "$jsdir/lib/pfun-io.js" 2>/dev/null || true; cp "$PFUN_IO" "$outdir/lib/pfun-io.js" 2>/dev/null || true; }
  fi
  timeout 90 node "$js"
  local rc=$?
  rm -rf "$outdir"
  if [ "$rc" -eq 0 ]; then pass=$((pass+1));
  else fail=$((fail+1)); failed_files+=("$f (exit $rc)"); fi
}

run_one 'bootstrap/test/compat_test_gen.pf'
run_one 'bootstrap/test/diag_test_gen.pf'
run_one 'bootstrap/test/imapi_test_gen.pf'
run_one 'bootstrap/test/imaps_test_gen.pf'
run_one 'bootstrap/test/lexer_test_gen.pf'
run_one 'bootstrap/test/listx_test_gen.pf'
run_one 'bootstrap/test/parser_test_gen.pf'
run_one 'bootstrap/test/strx_test_gen.pf'

echo
echo "========================================"
echo "Test files: $pass passed, $fail failed"
if [ "$fail" -ne 0 ]; then
  echo; echo "Failed:"
  for ff in "${failed_files[@]}"; do echo "  - $ff"; done
  exit 1
fi
echo "ALL TEST FILES PASSED"
exit 0
